"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Download, FileDown } from "lucide-react";
import { Button } from "@/components/ui/button";

interface GRNPDFProps {
    po: any;
    bill: any;
}

export default function GRNPDFDownload({ po, bill }: GRNPDFProps) {
    const generatePDF = () => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;

        // --- Header ---
        doc.setFillColor(245, 158, 11); // Amber-500
        doc.rect(0, 0, pageWidth, 40, "F");

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("BuildTrack", 14, 20);

        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text("Construction Management Platform", 14, 28);

        doc.setFontSize(24);
        doc.text("GOODS RECEIVED NOTE", pageWidth - 14, 25, { align: "right" });

        // --- Info Section ---
        doc.setTextColor(60, 60, 60);
        doc.setFontSize(10);

        const startY = 50;

        // Left specific details
        doc.text(`PO Number: #${po.po_number || po.id.slice(0, 8).toUpperCase()}`, 14, startY);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, startY + 6);
        doc.text(`Status: Completed & Verified`, 14, startY + 12);

        // Right specific details
        const rightX = pageWidth - 70;
        doc.text(`Supplier: Verified Supplier`, rightX, startY);
        doc.text(`Project: Central Site A`, rightX, startY + 6);
        doc.text(`Generated By: Manager`, rightX, startY + 12);

        // --- Table ---
        // Calculations
        const rate = 1000; // Mock rate since rate is not in PO explicitly, usually in Bill. Assuming basic. 
        // Wait, bill usually has amount.
        const qty = po.quantity || 0;
        const gstPercent = po.gst_rate || 0;
        const baseAmount = rate * qty; // Placeholder logic if actual amount missing
        const gstAmount = (baseAmount * gstPercent) / 100;
        const total = baseAmount + gstAmount;

        // Use autoTable for professional grid
        autoTable(doc, {
            startY: 75,
            head: [["Item ID", "Item Name", "Date", "Qty", "Rate/Unit", "GST %", "GST Amount", "Total"]],
            body: [
                [
                    po.material_id || "MAT-001",
                    po.material_name,
                    new Date(po.created_at).toLocaleDateString(),
                    qty,
                    `$${rate.toLocaleString()}`,
                    `${gstPercent}%`,
                    `$${gstAmount.toLocaleString()}`,
                    `$${total.toLocaleString()}`
                ]
            ],
            headStyles: { fillColor: [60, 60, 60], textColor: 255, fontStyle: 'bold' },
            bodyStyles: { textColor: 50 },
            alternateRowStyles: { fillColor: [245, 245, 245] },
            theme: 'grid'
        });

        // --- Footer ---
        const finalY = (doc as any).lastAutoTable.finalY + 20;

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("This is a computer-generated document. No signature required.", 14, finalY);

        doc.setFontSize(10);
        doc.setTextColor(245, 158, 11);
        doc.text("buildtrack.com", pageWidth - 14, finalY, { align: "right" });

        // Save
        doc.save(`GRN_${po.id.slice(0, 6)}.pdf`);
    };

    return (
        <Button
            variant="outline"
            size="sm"
            onClick={generatePDF}
            className="gap-2 text-amber-600 border-amber-200 hover:bg-amber-50"
        >
            <FileDown className="w-4 h-4" /> Download GRN
        </Button>
    );
}
